import test from 'node:test';
import assert from 'node:assert/strict';
import {newSave,draw,exchange,claimDaily,progress,validateSave,selectCard} from '../src/engine.js';
import {CARDS,CARD_BY_ID,POOLS,TOTAL_COPIES} from '../src/data.js';
import {loadSave,persist,SAVE_KEY,BACKUP_KEY} from '../src/storage.js';
const seeded=seed=>()=>{seed=(Math.imul(1664525,seed)+1013904223)>>>0;return seed/2**32;};
test('95 cards, five stars each, 475 effective copies, unique identifiers',()=>{assert.equal(CARDS.length,95);assert.equal(TOTAL_COPIES,475);assert.ok(CARDS.every(c=>c.max===5));assert.equal(new Set(CARDS.map(c=>c.id)).size,95);});
test('ten singles and one ten-pull have identical results and counters',()=>{const a=newSave(),b=newSave(),r1=seeded(42),r2=seeded(42);const ten=draw(a,10,r1).map(r=>r.id);const singles=Array.from({length:10},()=>draw(b,1,r2)).flat().map(r=>r.id);assert.deepEqual(ten,singles);assert.deepEqual(a.copies,b.copies);assert.equal(a.pity,b.pity);assert.equal(a.marks,10);});
test('SR guarantee on each fixed block, shared across singles',()=>{const s=newSave();for(let i=0;i<9;i++)draw(s,1,()=>.9);assert.equal(s.history.filter(h=>CARD_BY_ID[h.id].rarity==='SR').length,0);assert.equal(CARD_BY_ID[draw(s,1,()=>.9)[0].id].rarity,'SR');assert.equal(s.blockHasSR,false);assert.equal(s.tickets,50);});
test('SR boundary stays one paid card even when the natural roll is SSR',()=>{const s=newSave();for(let i=0;i<9;i++)draw(s,1,()=>.9);const r=draw(s,1,()=>0);assert.deepEqual(r.map(h=>CARD_BY_ID[h.id].rarity),['SR']);assert.equal(r[0].bonus,false);assert.equal(s.totalDraws,10);assert.equal(s.marks,10);assert.equal(s.tickets,50);assert.equal(s.received,10);validateSave(s);});
test('59th reserves SR and 60th keeps SSR hard pity with exactly 60 cards',()=>{const s=newSave();for(let i=0;i<58;i++)draw(s,1,()=>.9);const sr=draw(s,1,()=>.9);assert.equal(CARD_BY_ID[sr[0].id].rarity,'SR');const r=draw(s,1,()=>.9);assert.equal(r[0].source,'SSR保底');assert.equal(r.length,1);assert.equal(s.received,60);assert.equal(s.pity,0);validateSave(s);});
test('natural SSR resets pity',()=>{const s=newSave();draw(s,1,()=>.9);draw(s,1,()=>0);assert.equal(s.pity,0);});
test('SR earlier in block does not force extra SR',()=>{const s=newSave();draw(s,1,()=>.02);for(let i=0;i<9;i++)draw(s,1,()=>.9);assert.equal(CARD_BY_ID[s.history[0].id].rarity,'N');});
test('full card relative weight is 5 versus 100, not removal',()=>{const s=newSave(),pool=POOLS.SSR;s.copies[pool[0].id]=pool[0].max;assert.equal(selectCard(s,'SSR',()=>0).id,pool[0].id);assert.equal(selectCard(s,'SSR',()=>4.99/405).id,pool[0].id);assert.equal(selectCard(s,'SSR',()=>5.01/405).id,pool[1].id);});
test('full duplicates become glow, no extra star',()=>{const s=newSave(),c=POOLS.SSR[0];s.copies[c.id]=5;draw(s,1,()=>0);assert.equal(s.copies[c.id],5);assert.equal(s.glow,20);});
test('SSR exchange preserves pity, block and pull counter',()=>{const s=newSave();s.tickets=200;for(let i=0;i<101;i++)draw(s,1,()=>.9);const before=[s.pity,s.blockHasSR,s.totalDraws];exchange(s,POOLS.SSR[0].id);assert.deepEqual([s.pity,s.blockHasSR,s.totalDraws],before);assert.equal(s.marks,1);validateSave(s);});
test('glow exchange rejects insufficient currency and full cards',()=>{const s=newSave(),c=POOLS.N[0];assert.throws(()=>exchange(s,c.id));s.glow=10;exchange(s,c.id);assert.equal(s.glow,0);assert.equal(s.copies[c.id],1);s.copies[c.id]=c.max;s.glow=100;assert.throws(()=>exchange(s,c.id));assert.equal(s.glow,100);});
test('daily rewards cumulative total 1000 by day14, no duplicate claim',()=>{const s=newSave();for(let day=1;day<=14;day++){const d=`2026-09-${String(day).padStart(2,'0')}`;claimDaily(s,d);assert.throws(()=>claimDaily(s,d));if(day===3)assert.equal(s.tickets,250);if(day===7)assert.equal(s.tickets,530);}assert.equal(s.tickets,1000);assert.equal(s.days,14);validateSave(s);});
test('missed days do not reset streak; backward dates cannot claim',()=>{const s=newSave();claimDaily(s,'2026-09-01');claimDaily(s,'2026-09-10');assert.equal(s.days,2);assert.throws(()=>claimDaily(s,'2026-09-09'));});
test('completion requires all copies not just ownership',()=>{const s=newSave();for(const c of CARDS)s.copies[c.id]=1;assert.equal(progress(s).complete,false);for(const c of CARDS)s.copies[c.id]=c.max;assert.equal(progress(s).complete,true);assert.equal(progress(s).copies,475);assert.throws(()=>claimDaily(s));});
test('legacy R and N stars above five become glow without rejecting old history',()=>{
  const s=newSave(),ssr=POOLS.SSR[0],r=POOLS.R[0],n=POOLS.N[0];
  s.copies[ssr.id]=3;s.copies[r.id]=8;s.copies[n.id]=10;s.totalDraws=2;s.received=2;
  s.history=[{id:n.id,source:'抽取',bonus:false,isNew:false,before:9,after:10,glow:0,number:2,time:new Date().toISOString()}];
  const migrated=validateSave(s);
  assert.equal(migrated.copies[ssr.id],3);assert.equal(migrated.copies[r.id],5);assert.equal(migrated.copies[n.id],5);
  assert.equal(CARD_BY_ID[ssr.id].max,5);
  assert.equal(migrated.glow,14);assert.equal(migrated.history[0].after,10);
  assert.deepEqual(validateSave(migrated),migrated);
});
test('invalid import rejects versions, overflow, negative and unknown cards',()=>{for(const bad of [{...newSave(),version:2},{...newSave(),tickets:-1},{...newSave(),pity:60},{...newSave(),copies:{oops:1}},{...newSave(),copies:{[CARDS[0].id]:99}},{...newSave(),settings:{}}])assert.throws(()=>validateSave(bad));});
test('export wrapper roundtrip',()=>{const s=newSave();draw(s,10,seeded(100));assert.deepEqual(validateSave({format:'rigui-save',save:s}),s);});
test('insufficient ticket draw does not mutate',()=>{const s=newSave();s.tickets=9;const before=JSON.stringify(s);assert.throws(()=>draw(s,10));assert.equal(JSON.stringify(s),before);});
class Memory{data=new Map();getItem(k){return this.data.get(k)||null;}setItem(k,v){this.data.set(k,v);}}
test('valid backup recovers bad main',()=>{const st=new Memory(),s=newSave();persist(s,st);draw(s,1,()=>.9);persist(s,st);st.setItem(SAVE_KEY,'corrupt');assert.equal(loadSave(st).save.totalDraws,0);assert.equal(st.getItem(SAVE_KEY),'corrupt');});
test('corrupt both slots are preserved and blocked',()=>{const st=new Memory();st.setItem(SAVE_KEY,'bad');st.setItem(BACKUP_KEY,'badbackup');const r=loadSave(st);assert.equal(r.save,null);assert.equal(r.blocked,true);assert.equal(st.getItem(SAVE_KEY),'bad');});
test('storage denial blocks rather than pretending persistence',()=>{const st={getItem(){throw Error('denied');}};assert.equal(loadSave(st).blocked,true);assert.throws(()=>persist(newSave(),st));});
test('many seeds preserve guarantees and save validity',()=>{for(let seed=1;seed<=50;seed++){const s=newSave();s.tickets=200;const rng=seeded(seed);for(let b=0;b<20;b++){const r=draw(s,10,rng);assert.ok(r.some(h=>CARD_BY_ID[h.id].rarity==='SR'));assert.ok(s.pity<=59);validateSave(s);}}});
