import {mkdir,cp,readFile,stat} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {CARDS} from '../src/data.js';
const root=fileURLToPath(new URL('../',import.meta.url));
await mkdir(path.join(root,'dist'),{recursive:true});
for(const file of ['index.html','src','assets'])await cp(path.join(root,file),path.join(root,'dist',file),{recursive:true});
for(const art of new Set(CARDS.map(c=>c.art)))await stat(path.join(root,'dist',art));
const html=await readFile(path.join(root,'dist/index.html'),'utf8');
if(html.includes('https://'))throw new Error('Unexpected remote dependency');
console.log(`Build ready: ${CARDS.length} cards, ${new Set(CARDS.map(c=>c.art)).size} character studies. dist/`);
