import {CARDS,CARD_BY_ID,CHARACTERS,RARITIES,RULES,VERSION} from './data.js';
import {newSave,draw,exchange,claimDaily,localDay,progress,rewardForDay,validateSave} from './engine.js';
import {loadSave,persist,SAVE_KEY} from './storage.js';

const app=document.querySelector('#app'), modal=document.querySelector('#modal');
let loaded=loadSave(), state=loaded.save, blocked=loaded.blocked;
let page='home', hero=0, filter={rarity:'all',role:'all',owned:'all'}, busy=false, revealTimer, toastTimer;
const art=p=>CARDS.find(c=>c.characterId===p.id).art;
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(label,action,extra='',kind='')=>`<button class="${kind}" data-action="${action}" ${extra}>${label}</button>`;
function toast(message){const e=document.querySelector('#toast');e.textContent=message;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),4500);}
function panel(title,content,wide=false){clearTimeout(revealTimer);modal.className=wide?'wide':'';modal.innerHTML=`<header class="modal-head"><h2>${title}</h2>${button('关闭 ×','close','','quiet')}</header>${content}`;if(!modal.open)modal.showModal();}
function close(){clearTimeout(revealTimer);modal.close();}
function sound(){if(!state?.settings.sound)return;try{const AC=window.AudioContext||window.webkitAudioContext;const ctx=sound.ctx||(sound.ctx=new AC());ctx.resume();const o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.setValueAtTime(660,ctx.currentTime);o.frequency.exponentialRampToValueAtTime(330,ctx.currentTime+.3);g.gain.setValueAtTime(state.settings.volume*.08,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.45);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+.5);}catch{}}
async function transact(change,{replacement=false}={}){
  if(busy)return null;busy=true;
  const run=async()=>{
    const fresh=loadSave();
    if(fresh.blocked&&!replacement)throw new Error(fresh.warning);
    const next=structuredClone(fresh.save||newSave());
    const result=change(next);
    persist(next);state=next;blocked=false;render();return result;
  };
  try{return navigator.locks?await navigator.locks.request('rigui-save-write',run):await run();}
  catch(error){toast(error.message||'保存失败，操作未完成。请检查浏览器存储权限。');return null;}
  finally{busy=false;}
}
function tile(c,{result=null}={}){
 const n=state.copies[c.id]||0,p=CHARACTERS[c.characterIndex];
 return `<button class="card ${c.rarity} ${!n?'unowned':''}" data-action="detail" data-id="${c.id}" aria-label="${p.name}·${c.title} ${c.rarity} ${n}/${c.max}星"><img src="${c.art}" alt="${p.name}角色样卡" loading="lazy"><span class="rarity">${c.rarity}</span>${result?.isNew?'<span class="new">初见</span>':''}<div class="card-name"><small>${p.name}</small><strong>${c.title}</strong><span>${result?.glow?`余晖 +${result.glow}`:`${n===c.max?'满星':`${n} / ${c.max} 星`}`}</span></div>${result?.bonus?'<span class="bonus">额外 SR 保底</span>':''}</button>`;
}
function render(){
 if(!state||blocked){app.innerHTML=`<main class="recovery"><div class="wordmark">日晷</div><h1>先守好你的存档</h1><p>${esc(loaded.warning||'存储暂不可用，请检查浏览器权限。')}</p><div class="actions">${button('导出原始存档','raw')}${button('导入备份','import')}${button('重新开始','reset','','danger')}</div></main>`;return;}
 const p=progress(state);document.documentElement.classList.toggle('reduced',state.settings.reduced);
 app.innerHTML=`<div class="shell"><aside class="rail"><button class="brand" data-action="nav" data-page="home" aria-label="日晷首页">日<br>晷<span>一卷山河</span></button><nav aria-label="主要导航">${[['home','展卷','◈'],['collection','图鉴','▤'],['exchange','兑换','◇'],['history','纪事','◷'],['settings','设置','⚙']].map(([id,name,icon])=>`<button data-action="nav" data-page="${id}" ${page===id?'aria-current="page"':''}><span>${icon}</span>${name}</button>`).join('')}</nav><span class="rail-foot">古代线 · 免费</span></aside><main><header class="topbar"><span class="breadcrumb">日晷 <i>/</i> ${ {home:'一卷山河',collection:'百卷图鉴',exchange:'以印换卷',history:'展卷纪事',settings:'偏好与存档'}[page]}</span><div class="currencies"><span title="抽取卡牌的晷签">晷签 <b>${state.tickets}</b></span><span title="每抽获得1枚，100枚兑换指定SSR">印记 <b>${state.marks}</b></span><span title="满星后重复卡转换">余晖 <b>${state.glow}</b></span>${button(state.lastClaim>=localDay()?'今日已领':'领取签赠','rewards','','gift')}</div></header><div id="page">${page==='home'?home(p):page==='collection'||page==='exchange'?collection(p):page==='history'?history():settings()}</div><footer class="footer"><span>水墨入卷，静候相逢。</span><span>本地存档 · ${VERSION} 样卡试玩版 ${button('抽取规则','rules','','text-button')}</span></footer></main></div>`;
}
function home(p){const c=CHARACTERS[hero];return `<section class="home"><div class="hero-art"><img src="${art(c)}" alt="${c.name}，水墨角色立绘"><span class="art-seal">${c.seal}</span></div><div class="hero-copy"><span class="eyebrow">常驻卡池 / 壹</span><h1>一卷<span>山河</span></h1><p class="poem">${c.motto}</p><div class="featured"><span class="red-seal">${c.seal}</span><div><small>${c.office}</small><h2>${c.name}</h2></div></div><p class="intro">循光展卷，收录此间风华。<br>五位故人，九十五卷，皆可免费收集。</p><div class="hero-choices" aria-label="切换展示角色">${CHARACTERS.map((person,i)=>`<button data-action="hero" data-index="${i}" aria-label="展示${person.name}" aria-pressed="${i===hero}"><img src="${art(person)}" alt=""><span>${person.name}</span></button>`).join('')}</div></div><div class="draw-dock"><div class="journey"><div><span>${p.complete?'百卷已成':'图鉴进度'}</span><strong>${p.owned}<small> / 95</small></strong></div><div class="track"><span style="width:${p.copies/p.max*100}%"></span></div><small>满星 ${p.full} / 95 · 累计 ${p.copies} / 790 份</small></div><div class="pull-area"><div class="pity">SSR 最多再 <b>${60-state.pity}</b> 抽 <span>本轮SR ${state.blockHasSR?'已获得':`最多再 ${10-state.totalDraws%10} 抽`}</span></div><div class="pull-buttons">${button('展卷一次 <small>晷签 × 1</small>','draw','data-count="1"'+(state.tickets<1?' disabled':''),'pull single')}${button('展卷十次 <small>晷签 × 10</small>','draw','data-count="10"'+(state.tickets<10?' disabled':''),'pull primary')}</div><small class="hint">单抽累计同享保底 · SSR 不替代 SR</small></div></div></section>`;}
function collection(p){const exchangeMode=page==='exchange';const visible=CARDS.filter(c=>(filter.rarity==='all'||c.rarity===filter.rarity)&&(filter.role==='all'||c.characterId===filter.role)&&(filter.owned==='all'||filter.owned==='missing'&&!(state.copies[c.id])||filter.owned==='owned'&&state.copies[c.id]>0||filter.owned==='unfinished'&&(state.copies[c.id]||0)<c.max||filter.owned==='full'&&state.copies[c.id]===c.max));return `<section class="page-content"><div class="section-title"><div><span class="eyebrow">${exchangeMode?'以印换卷':'珍藏此间'}</span><h1>${exchangeMode?'定向兑换':'百卷图鉴'}</h1></div><p>${exchangeMode?'SSR：100印记 / 份<br>N：10余晖 · R：30余晖 · SR：80余晖':`已收录 <b>${p.owned}</b> / 95 · 已满星 <b>${p.full}</b> / 95`}</p></div>${p.complete?'<div class="complete-banner">百卷已成 · 此间风华，尽入君藏。你已完成全部 790 份收集。</div>':''}<div class="filters"><label>稀有度 <select data-filter="rarity"><option value="all">全部</option>${RARITIES.map(r=>`<option ${filter.rarity===r?'selected':''}>${r}</option>`).join('')}</select></label><label>人物 <select data-filter="role"><option value="all">全部人物</option>${CHARACTERS.map(c=>`<option value="${c.id}" ${filter.role===c.id?'selected':''}>${c.name}</option>`).join('')}</select></label><label>收集 <select data-filter="owned">${[['all','全部状态'],['missing','未获得'],['owned','已获得'],['unfinished','未满星'],['full','已满星']].map(([v,l])=>`<option value="${v}" ${filter.owned===v?'selected':''}>${l}</option>`).join('')}</select></label><small>${visible.length} 卷</small></div><p class="sample-note">当前为角色样卡版：95个卡牌条目共用5张角色插画，独立卡面尚未制作。点击卡牌查看星级${exchangeMode?'并兑换':''}。</p><div class="card-grid">${visible.map(c=>tile(c)).join('')||'<p class="empty">没有符合筛选条件的卡牌。</p>'}</div></section>`;}
function history(){return `<section class="page-content"><div class="section-title"><div><span class="eyebrow">相逢有迹</span><h1>展卷纪事</h1></div><p>累计 ${state.totalDraws} 抽 · 记录最近300次获得</p></div><div class="history-list">${state.history.map(h=>{const c=CARD_BY_ID[h.id];return `<div><time>${esc(new Date(h.time).toLocaleString('zh-CN'))}</time><span class="pill ${c.rarity}">${c.rarity}</span><strong>${CHARACTERS[c.characterIndex].name} · ${c.title}</strong><span>${h.source}</span><small>${h.glow?`余晖 +${h.glow}`:`${h.before} → ${h.after} 星`}</small></div>`;}).join('')||'<p class="empty">尚未展卷。去与第一位故人相逢吧。</p>'}</div></section>`;}
function settings(){return `<section class="page-content settings"><div class="section-title"><div><span class="eyebrow">自在游玩</span><h1>偏好与存档</h1></div></div><div class="setting-grid"><section class="paper"><h2>展卷体验</h2>${[['fast','快速展卷','直接展示结果，省略揭晓动画。'],['rareEffects','稀有卡强调','为SSR结果增加静态金色描边。'],['reduced','减少动态效果','关闭界面过渡与卡牌揭晓动画。'],['sound','交互音效','开启轻提示音，无配音及背景音乐。']].map(([k,t,d])=>`<label class="setting"><span><b>${t}</b><small>${d}</small></span><input type="checkbox" data-setting="${k}" ${state.settings[k]?'checked':''}></label>`).join('')}<label class="setting"><span>音量</span><input aria-label="音量" type="range" data-setting="volume" min="0" max="1" step="0.05" value="${state.settings.volume}"></label></section><section class="paper"><h2>存档由你保管</h2><p>进度仅保存在当前浏览器。清理网站数据、更换设备或更换网址，都不会自动迁移存档。建议定期导出。</p><div class="actions">${button('导出存档','export','','primary')}${button('导入存档','import')}</div><p class="sample-note">导入会覆盖当前进度，确认前请先导出备份。游戏无账号、无付费、无联网校验。</p><hr><h3>重新开始</h3><p>清除本机进度，恢复初始60张晷签。</p>${button('重置进度','reset','','danger')}</section></div></section>`;}
function detail(id){const c=CARD_BY_ID[id];if(!c)return;const p=CHARACTERS[c.characterIndex],n=state.copies[id]||0,cost=c.rarity==='SSR'?100:RULES.costs[c.rarity],currency=c.rarity==='SSR'?'印记':'余晖';panel(`${p.name} · ${c.title}`,`<div class="detail"><img src="${c.art}" alt="${p.name}角色样卡"><div><span class="pill ${c.rarity}">${c.rarity}</span><h2>${c.title}</h2><p>${p.motto}</p><p>${c.description}</p><div class="stars" aria-label="${n}/${c.max}星">${'◆'.repeat(n)}<span>${'◇'.repeat(c.max-n)}</span></div><p>${n} / ${c.max} 星 · ${n===c.max?'已满星':n?'再次获得自动升星':'尚未获得'}</p><small>满星后重复获得，转为 ${RULES.overflow[c.rarity]} 余晖。满星卡仍留在卡池，同稀有度内相对权重降至未满星卡的5%。</small><div class="actions">${button(n===c.max?'已满星':`兑换一份 · ${cost}${currency}`,'exchange',`data-id="${id}" ${n===c.max?'disabled':''}`,'primary')}</div><p class="sample-note">此为共用角色样卡；兑换只获得一份，不直接满星。</p></div></div>`,true);}
function results(items,count){const reduce=state.settings.fast||state.settings.reduced||matchMedia('(prefers-reduced-motion: reduce)').matches;panel('此番相逢',`<p class="result-summary">消耗 ${count} 晷签 · 获得 ${items.length} 份${items.length>count?'（含额外SR保底）':''} · 印记 +${count}</p><div class="results ${reduce?'':'veiled'} ${state.settings.rareEffects?'rare-on':''}">${items.map(r=>tile(CARD_BY_ID[r.id],{result:r})).join('')}</div><div class="result-actions">${button('一键跳过','skip',reduce?'hidden':'')}${button('收入图鉴','close','','primary')}${button('再展十卷','draw','data-count="10"'+(state.tickets<10?' disabled':''))}</div>`,true);if(!reduce)revealTimer=setTimeout(reveal,1100);}
function reveal(){clearTimeout(revealTimer);modal.querySelector('.results')?.classList.remove('veiled');const b=modal.querySelector('[data-action="skip"]');if(b)b.hidden=true;}
function rewards(){const p=progress(state),claimed=state.lastClaim>=localDay();panel('每日签赠',`<div class="reward-body"><span class="eyebrow">不必赶路，相逢自有时</span><h3>已领取 ${state.days} 天</h3><p>每天手动领取50晷签。按累计领取天数计算，中断不清零。</p><div class="milestones">${[3,7,14].map(d=>`<div class="${state.days>=d?'done':''}"><small>累计第${d}天</small><b>+${RULES.milestones[d]}</b><span>${state.days>=d?'已领取':'额外晷签'}</span></div>`).join('')}</div><p>初始60晷签，累计领取14天共可获得1000晷签。此后每天50，直到全图鉴满星。</p>${button(p.complete?'已完成全图鉴':claimed?'今日已领取':`领取今日 ${rewardForDay(state.days+1)} 晷签`,'claim',p.complete||claimed?'disabled':'','primary')}<p class="sample-note">领取日期以本机时间为准。调整时间可能导致暂时无法领取。</p></div>`);}
function rules(){panel('抽取规则',`<div class="rules"><h3>常驻单一卡池 · 95卷</h3><table><thead><tr><th>稀有度</th><th>基础概率</th><th>卡数</th><th>满星份数</th></tr></thead><tbody>${RARITIES.map(r=>`<tr><td>${r}</td><td>${RULES.rates[r]*100}%</td><td>${RULES.counts[r]*5}</td><td>${RULES.caps[r]}</td></tr>`).join('')}</tbody></table><p>基础概率不含保底。每次抽取独立计算，展示角色不会提高该角色概率。</p><h3>SR与SSR各自保底</h3><p>SR按账号总抽数分组：第1–10、11–20抽，以此类推，每组至少一张SR。单抽与十连共享进度。如果组内尚无SR，末抽非SSR时转为SR；末抽为SSR时，保留SSR并额外补发一张SR，不多扣晷签。</p><p>SSR最多60抽必出，无软保底。抽到SSR重置SSR计数；兑换SSR不重置。额外补发的SR不增加抽数或印记。</p><h3>满星与兑换</h3><p>每抽获得1印记，100印记可兑换任意未满星SSR的一份。满星卡不会移除：同稀有度内，未满星卡权重100、满星卡权重5，稀有度基础概率不变。</p><p>满星后的重复卡转为余晖：N 1、R 3、SR 8、SSR 20。兑换一份N / R / SR分别需要10 / 30 / 80余晖。余晖不能兑换SSR。</p><p>95卷全部满星需要790份有效卡牌。集齐时间受随机结果和兑换选择影响，不保证14天满星。</p></div>`,true);}
function download(data,name){const url=URL.createObjectURL(new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function importSave(){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{try{const file=input.files[0];if(!file)return;if(file.size>2*1024*1024)throw new Error('文件超过2MB，请选择日晷导出的JSON存档。');const candidate=validateSave(JSON.parse(await file.text()));const p=progress(candidate);panel('确认导入存档',`<p>将替换当前浏览器进度：累计 ${candidate.totalDraws} 抽、收录 ${p.owned} 卷、满星 ${p.full} 卷。</p><p>建议先导出当前存档。此操作无法自动合并两份进度。</p><div class="actions">${button('先导出当前存档','export')}${button('确认替换','confirm-import','','primary')}</div>`);modal.querySelector('[data-action="confirm-import"]').onclick=async()=>{const ok=await transact(s=>{Object.assign(s,candidate);return true;},{replacement:true});if(ok){close();toast('存档已导入。');}};}catch(e){toast(e.message);}};input.click();}
function reset(){panel('重置进度',`<p>将清除当前进度并恢复初始60晷签。请先导出存档。</p><div class="actions">${button('导出存档','export')}</div><label class="reset-label">输入“重新开始”确认 <input id="reset-word" autocomplete="off"></label>${button('确认重置','confirm-reset','','danger')}`);modal.querySelector('[data-action="confirm-reset"]').onclick=async()=>{if(modal.querySelector('#reset-word').value!=='重新开始'){toast('请输入“重新开始”以确认。');return;}const ok=await transact(s=>{Object.assign(s,newSave());return true;},{replacement:true});if(ok){close();toast('已重新开始。');}};}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;if(['confirm-import','confirm-reset'].includes(a))return;
 if(a==='close')close();else if(a==='nav'){page=b.dataset.page;render();}else if(a==='hero'){hero=Number(b.dataset.index);render();}else if(a==='detail')detail(b.dataset.id);else if(a==='rules')rules();else if(a==='rewards')rewards();else if(a==='skip')reveal();else if(a==='draw'){const count=Number(b.dataset.count);const result=await transact(s=>draw(s,count));if(result){sound();results(result,count);}}else if(a==='claim'){const amount=await transact(s=>claimDaily(s));if(amount!==null){rewards();toast(`已领取 ${amount} 晷签。`);}}else if(a==='exchange'){const result=await transact(s=>exchange(s,b.dataset.id));if(result){detail(b.dataset.id);toast('兑换成功，已收入图鉴。');}}else if(a==='export'){if(state)download({format:'rigui-save',exportedAt:new Date().toISOString(),save:state},`日晷存档-${localDay()}.json`);else toast('当前存档无法读取，请导出原始存档。');}else if(a==='raw'){try{download(localStorage.getItem(SAVE_KEY)||'null','日晷原始存档.json');}catch{toast('浏览器禁止读取存储。');}}else if(a==='import')importSave();else if(a==='reset')reset();
});
document.addEventListener('change',async e=>{if(e.target.dataset.filter){filter[e.target.dataset.filter]=e.target.value;render();}if(e.target.dataset.setting){const k=e.target.dataset.setting,v=k==='volume'?Number(e.target.value):e.target.checked;await transact(s=>{s.settings[k]=v;return true;});}});
window.addEventListener('storage',e=>{if(e.key!==SAVE_KEY)return;loaded=loadSave();state=loaded.save;blocked=loaded.blocked;close();render();toast('已同步另一窗口的进度。');});
modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close();}});
render();if(loaded.warning)toast(loaded.warning);
