import {CARDS,CARD_BY_ID,CHARACTERS} from './data.js?v=20261004-r10';
import {newSave,draw,progress,claimDaily,localDay,exchange,validateSave} from './engine.js?v=20261004-r10';
import {loadSave,persist} from './storage.js?v=20261004-r10';
import {GameAudio} from './audio.js?v=20261004-r10';
import {pityCopy,starsMarkup,collectionPercent,drawArt,firstMeetingMarkup,drawSummary,collectionFilterButton,collectionFilterMarkup,collectionFilterChoices} from './presentation.js?v=20261004-r10';
import {watchResultImages,watchCollectionImages} from './result-images.js?v=20261004-r10';
import {fitResultCards} from './presentation.js?v=20261004-r10';
import {exchangeSuccessMarkup,watchExchangeImage,showExchangeError} from './exchange-feedback.js?v=20261004-r10';
import {installPageScroll} from './page-scroll.js?v=20261004-r10';
const app=document.querySelector('#app'),modal=document.querySelector('#modal'),toast=document.querySelector('#toast'),rotatePrompt=document.querySelector('.rotate'),rotateCountdown=document.querySelector('.rotate-countdown');let state=loadSave().save||newSave(),index=0,view='home',timer,toastTimer,rotateTimer,rotateTick,drawRevealTimer,drawRevealSkip,skipRevealClick=false,openCurrency=null,openProgress=false,filter={rarity:'all',role:'all',owned:'all'};
const reviewParams=new URLSearchParams(location.search),localReview=['localhost','127.0.0.1'].includes(location.hostname)||reviewParams.get('review')==='1';if(localReview){state.tickets=Math.max(state.tickets,9999);persist(state);}
const ssr=CARDS.filter(c=>c.rarity==='SSR');
installPageScroll(app);
let galleryRoot=null,disposeGallery=()=>{},disposeFit=()=>{};
new MutationObserver(()=>{const root=app.querySelector('.collection-page');if(root!==galleryRoot){disposeGallery();galleryRoot=root;disposeGallery=root?watchCollectionImages(root):()=>{};}}).observe(app,{childList:true});
new MutationObserver(()=>{disposeFit();disposeFit=modal.classList.contains('draw-modal')?fitResultCards(modal)||(()=>{}):()=>{};}).observe(modal,{childList:true});
const audio=new GameAudio(()=>state.settings);
document.addEventListener('pointerdown',()=>audio.unlock(),{capture:true});
document.addEventListener('keydown',()=>audio.unlock(),{capture:true});
document.addEventListener('visibilitychange',()=>audio.setHidden(document.hidden));
window.addEventListener('pagehide',()=>audio.setHidden(true));
window.addEventListener('pageshow',()=>audio.setHidden(document.hidden));
function sideNav(){return '<nav class="side-nav" aria-label="主要导航"><button data-home '+(view==='home'?'aria-current="page"':'')+'><b>晷</b><span>主页</span></button><button data-collection '+(view==='collection'?'aria-current="page"':'')+'><b>册</b><span>图鉴</span></button><button data-history '+(view==='history'?'aria-current="page"':'')+'><b>录</b><span>纪事</span></button><button data-settings '+(view==='settings'?'aria-current="page"':'')+'><b>设</b><span>设置</span></button></nav>';}
function currencyItems(){return [['晷签',state.tickets,'用于展卷的珍贵道具'],['印记',state.marks,'每一次展卷可获取一个，满100个可兑换SSR'],['余晖',state.glow,'满星卡溢出时获得的稀有道具，可用于兑换卡面']];}
function currencyItemsMarkup(){return currencyItems().map(([name,amount,tip])=>{const open=openCurrency===name;return '<button type="button" class="wallet-item'+(open?' is-open':'')+'" data-currency-tip="'+name+'" aria-expanded="'+open+'" aria-label="'+name+' '+amount+'，点击查看说明"><small>'+name+'</small><strong>'+amount+'</strong><span class="wallet-tip" role="tooltip">'+tip+'</span></button>';}).join('');}
function currencyStrip(){return '<span class="currency-strip" aria-label="持有货币">'+currencyItemsMarkup()+'</span>';}
function utilityHeader(title){return '<header class="collection-top"><span class="eyebrow">'+title+'</span>'+currencyStrip()+'</header>';}
function homeWallet(){return '<aside class="home-wallet" aria-label="持有货币">'+currencyItemsMarkup()+'</aside>';}
function progressRingMarkup(p,location){const percent=collectionPercent(p);return '<button type="button" class="progress-ring '+location+'-ring'+(openProgress?' is-open':'')+'" data-progress-tip aria-expanded="'+openProgress+'" aria-label="图鉴总收集度 '+percent+'%，点击查看说明" style="--pct:'+percent+'%"><span class="progress-ring-label">已收集</span><strong>'+percent+'%</strong><span class="progress-tip" role="tooltip">图鉴总收集度</span></button>';}
function historyPage(){const rows=state.history.map(h=>{const c=CARD_BY_ID[h.id];return '<div class="history-row '+c.rarity+'"><time>'+new Date(h.time).toLocaleString('zh-CN')+'</time><span class="history-rarity '+c.rarity+'">'+c.rarity+'</span><strong>'+c.displayName+' · '+c.title+'</strong><span>'+h.source+'</span><small>'+(h.glow?'余晖 +'+h.glow:h.before+' → '+h.after+' 星')+'</small></div>';}).join('')||'<p class="empty">尚未展卷。</p>';app.innerHTML=sideNav()+'<main class="utility-page">'+utilityHeader('展卷纪事')+'<section class="utility-heading"><h1>相逢有迹</h1><p>累计 '+state.totalDraws+' 抽 · 保存最近300次获得记录</p></section><div class="history-table">'+rows+'</div></main>';}
function settingsPage(){const toggles=[['sound','声音总开关','关闭后静音所有音乐和音效。'],['music','背景音乐','古风器乐《庭院叙事》，首次点击页面后播放。'],['effects','抽卡音效','展卷翻页与木简落桌声。'],['fast','快速展卷','直接展示抽卡结果。'],['rareEffects','稀有卡强调','强化稀有卡的荧光效果。'],['showNew','显示初见','在首次获得的卡面左侧显示竖排「初见」。'],['reduced','减少动态效果','关闭轮播和界面过渡。']].map(([key,title,desc])=>'<label class="setting-row"><span><b>'+title+'</b><small>'+desc+'</small></span><input type="checkbox" data-setting="'+key+'" '+(state.settings[key]?'checked':'')+'></label>').join('');app.innerHTML=sideNav()+'<main class="utility-page">'+utilityHeader('偏好与存档')+'<section class="utility-heading"><h1>设置</h1><p>进度保存在当前浏览器，建议定期导出备份。</p></section><div class="settings-panels"><section><h2>展卷体验</h2>'+toggles+'<label class="setting-row"><span><b>总音量</b><small>音乐与音效的播放音量</small></span><input type="range" aria-label="总音量" data-volume min="0" max="100" value="'+Math.round(state.settings.volume*100)+'"></label><div class="settings-actions"><button data-rules>查看抽取规则</button></div></section><section><h2>存档由你保管</h2><p>更换设备、网址或清理浏览器数据时，需要手动导入备份。</p><div class="settings-actions"><button data-export>导出存档</button><button class="primary" data-import>导入存档</button></div><hr><h3>重新开始</h3><p>恢复初始60张晷签，并清空当前收集、兑换与纪事记录。请先导出备份。</p><button class="danger" data-reset>重置进度</button></section></div></main>';}
function collection(){const p=progress(state),visible=CARDS.filter(c=>{const n=state.copies[c.id]||0;return (filter.rarity==='all'||c.rarity===filter.rarity)&&(filter.role==='all'||c.characterId===filter.role)&&(filter.owned==='all'||filter.owned==='missing'&&n===0||filter.owned==='owned'&&n>0||filter.owned==='unfinished'&&n<c.max||filter.owned==='full'&&n>=c.max);}),cards=visible.map(c=>{const n=state.copies[c.id]||0;return '<button class="collection-card '+c.rarity+(n===0?' unowned':' owned')+(n>=c.max?' full-star':'')+'" data-card="'+c.id+'"><img data-preview-src="'+drawArt(c)+'" data-full-src="'+c.art+'" width="480" height="720" decoding="async" alt="'+c.displayName+'·'+c.title+'"><span class="collection-rarity">'+c.rarity+'</span><div><small>'+c.displayName+'</small><strong>'+c.title+'</strong>'+starsMarkup(c.rarity,n)+'</div></button>';}).join('')||'<p class="empty">没有符合筛选条件的卡牌。</p>';app.innerHTML=sideNav()+'<main class="collection-page"><header class="collection-top"><span class="eyebrow">珍藏此间</span>'+currencyStrip()+'</header><section class="collection-heading"><div><h1>百卷图鉴 '+progressRingMarkup(p,'collection')+'</h1><p>收录 '+p.owned+' / 95 卷 · 满星 '+p.full+' / 95 卷 · 点击卡面可查看并兑换</p></div></section><div class="collection-filters">'+['rarity','role','owned'].map(key=>collectionFilterButton(key,filter[key],CHARACTERS)).join('')+'<span>'+visible.length+' 卷</span></div><div class="collection-grid">'+cards+'</div></main>';}
function render(){audio.sync();if(view==='collection'){collection();return;}if(view==='history'){historyPage();return;}if(view==='settings'){settingsPage();return;}const p=progress(state),c=CHARACTERS[ssr[index].characterIndex];const slides=ssr.map((x,i)=>'<img class="carousel-slide '+(i===index?'active':'')+'" src="'+x.art+'" alt="'+x.displayName+' SSR卡面">').join('');const dots=ssr.map((x,i)=>'<button class="dot-button" data-i="'+i+'" aria-current="'+(i===index)+'"><span></span></button>').join('');const choices=ssr.map((x,i)=>'<button data-i="'+i+'" aria-pressed="'+(i===index)+'"><img src="'+x.art+'" alt=""><span>'+x.displayName+'</span></button>').join('');app.innerHTML=sideNav()+'<main class="demo-shell"><div class="home-wash"></div>'+homeWallet()+'<div class="hero-copy"><span class="eyebrow">常驻卡池 / 壹</span><div class="hero-title"><h1>一卷<span>山河</span></h1><button class="daily-gift" data-daily '+(state.lastClaim>=localDay()?'disabled':'')+'>'+(state.lastClaim>=localDay()?'今日签赠已领':'领取今日赠签')+'</button></div><p class="poem">'+c.motto+'</p><p class="intro">循光展卷，收录此间风华。<br>五位故人，九十五卷，皆可免费收集。</p></div><section class="hero-carousel"><div class="carousel-stage">'+slides+'</div><div class="carousel-dots">'+dots+'</div></section><aside class="identity-dock"><div class="featured"><span class="red-seal">'+c.seal+'</span><div><small>'+c.office+'</small><h2>'+ssr[index].displayName+'</h2></div>'+progressRingMarkup(p,'home')+'</div><p class="identity-copy">'+c.motto+'<br>'+c.description+'</p><div class="hero-choices">'+choices+'</div><button class="collection-link" data-collection>图鉴　'+p.owned+' / 95</button></aside><div class="draw-dock"><div class="journey"><span>图鉴进度</span><strong>'+p.owned+'<small> / 95</small></strong><div class="track"><span style="width:'+(p.owned/95*100)+'%"></span></div></div><div class="pull-area"><div class="pity"><span>'+pityCopy(state.pity).ssr+'</span><span>'+pityCopy(state.pity).sr+'</span></div><div class="pull-buttons"><button data-draw="1" '+(state.tickets<1?'disabled':'')+'>展卷一次<small>晷签 × 1</small></button><button class="primary" data-draw="10" '+(state.tickets<10?'disabled':'')+'>展卷十次<small>晷签 × 10</small></button></div><small class="hint">'+pityCopy(state.pity).shared+'</small></div></div></main>';}
function notify(message){toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),3200);}
function playScrollSound(){audio.playPages();}
function finishDrawReveal(){audio.stopPages();clearTimeout(drawRevealTimer);drawRevealTimer=null;if(drawRevealSkip)document.removeEventListener('pointerdown',drawRevealSkip,true);drawRevealSkip=null;modal.classList.remove('scroll-opening');}
function startDrawReveal(){clearTimeout(drawRevealTimer);skipRevealClick=false;if(drawRevealSkip)document.removeEventListener('pointerdown',drawRevealSkip,true);modal.classList.remove('scroll-opening');void modal.offsetWidth;if(!modal.open)modal.showModal();if(state.settings.fast||state.settings.reduced||matchMedia('(prefers-reduced-motion: reduce)').matches)return;modal.classList.add('scroll-opening');drawRevealSkip=event=>{if(!event.target.closest('[data-retry-images]'))skipRevealClick=true;finishDrawReveal();};document.addEventListener('pointerdown',drawRevealSkip,{capture:true,once:true});playScrollSound();drawRevealTimer=setTimeout(finishDrawReveal,2400);}
function showResults(items,count){const cards=items.map(r=>{const c=CARD_BY_ID[r.id];return '<article class="result-card '+c.rarity+(r.after>=c.max?' full-star':'')+'"><img src="'+drawArt(c)+'" data-full-src="'+c.art+'" data-preview-src="'+drawArt(c)+'" decoding="async" fetchpriority="high" alt="'+c.displayName+'·'+c.title+'"><span class="collection-rarity">'+c.rarity+'</span>'+firstMeetingMarkup(r,state.settings)+'<div><small>'+c.displayName+'</small><strong>'+c.title+'</strong>'+starsMarkup(c.rarity,r.after)+'</div></article>';}).join(''),redrawCount=count===1?1:10,redrawLabel=count===1?'再展一卷':'再展十卷';if(modal.open)modal.close();modal.className='draw-modal '+(count===10?'ten-pull-modal':'single-pull-modal')+(items.length>10?' bonus-result':'');modal.innerHTML='<div class="scroll-surface"><div class="scroll-content"><header class="modal-head"><h2>此番相逢</h2></header><p class="result-summary">'+drawSummary(items,count)+'</p><div class="draw-results">'+cards+'</div><div class="result-actions"><p class="result-image-status" data-image-status role="status"></p><button data-retry-images hidden>重试卡面</button><button class="primary result-redraw" data-redraw="'+redrawCount+'" '+(state.tickets<redrawCount?'disabled':'')+'>'+redrawLabel+'</button></div></div></div><i class="scroll-roller scroll-roller-left" aria-hidden="true"></i><i class="scroll-roller scroll-roller-right" aria-hidden="true"></i><p class="scroll-skip-hint">点击任意位置跳过动画</p>';watchResultImages(modal);startDrawReveal();}
function showExchangeSuccess(result){const card=CARD_BY_ID[result.id];modal.className='exchange-modal';modal.setAttribute('aria-label','兑换成功');modal.innerHTML=exchangeSuccessMarkup(card,result);document.documentElement.classList.add('detail-open');if(!modal.open)modal.showModal();modal.querySelector('.exchange-heading').focus({preventScroll:true});watchExchangeImage(modal);audio.playExchange();}
function showDetail(id){const c=CARD_BY_ID[id],n=state.copies[id]||0,cost=c.rarity==='SSR'?100:{SR:80,R:30,N:10}[c.rarity],currency=c.rarity==='SSR'?'印记':'余晖',full=n>=c.max;modal.className='detail-modal';modal.setAttribute('aria-label','卡牌详情');modal.innerHTML='<header class="modal-head"><h2>'+c.displayName+' · '+c.title+'</h2><button data-close>关闭 ×</button></header><div class="card-detail"><img src="'+c.art+'" alt="'+c.displayName+'·'+c.title+'"><div class="detail-info"><span class="collection-rarity">'+c.rarity+'</span><p class="detail-description">'+c.description+'</p>'+starsMarkup(c.rarity,n)+'<p class="detail-status">'+(full?'已满星':'再次获得一份将自动点亮下一颗星。')+'</p><button class="primary" data-exchange="'+id+'" '+(full?'disabled':'')+'>兑换一份 · '+cost+currency+'</button></div></div>';document.documentElement.classList.add('detail-open');if(!modal.open)modal.showModal();}
function showRules(){modal.className='';modal.innerHTML='<header class="modal-head"><h2>抽取规则</h2><button data-close>关闭 ×</button></header><div class="rules-copy"><h3>单一卡池</h3><p>SSR 1.5%、SR 3.5%、R 25%、N 70%。</p><h3>保底</h3><p>SSR最多60抽获得。每十抽至少获得一张SR；单抽与十连都享有SR保底机制，十连中出现的SSR不能替代保底SR。连续9次未获得SR，下一次在实际抽取中保证SR；SSR硬保底同时临近时提前安排SR。十连只消耗10晷签、获得10张卡，不额外补发。</p><h3>满星与兑换</h3><p>满星卡仍留在卡池，但会降低满星卡的出卡概率。每抽获得1印记，100印记可兑换任意未满星SSR卡一张；余晖可兑换N、R、SR卡。</p></div>';if(!modal.open)modal.showModal();}
function showReset(){modal.className='';modal.innerHTML='<header class="modal-head"><h2>确认重新开始</h2><button data-close>关闭 ×</button></header><div class="reset-confirm"><p>这会清空当前收集、晷签、印记、余晖与纪事记录，并恢复初始60张晷签。</p><p>此操作无法自动撤销，建议先导出存档。</p><div class="result-actions"><button data-close>取消</button><button class="danger" data-confirm-reset>确认重置</button></div></div>';if(!modal.open)modal.showModal();}
function doDraw(count){try{const items=draw(state,count);persist(state);render();showResults(items,count);}catch(error){notify(error.message);}}
function exportSave(){const blob=new Blob([JSON.stringify({format:'rigui-save',exportedAt:new Date().toISOString(),save:state},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='日晷存档-'+localDay()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function importSave(){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{try{const raw=JSON.parse(await input.files[0].text()),candidate=validateSave(raw);state=candidate;persist(state);render();notify('存档已导入。');}catch(error){notify(error.message||'存档导入失败。');}};input.click();}
function closeCurrencyTips(except){if(!except)openCurrency=null;document.querySelectorAll('.wallet-item.is-open').forEach(item=>{if(item!==except){item.classList.remove('is-open');item.setAttribute('aria-expanded','false');}});}
function toggleCurrencyTip(item){const shouldOpen=!item.classList.contains('is-open');closeCurrencyTips(item);openCurrency=shouldOpen?item.dataset.currencyTip:null;item.classList.toggle('is-open',shouldOpen);item.setAttribute('aria-expanded',String(shouldOpen));}
function closeProgressTip(){openProgress=false;document.querySelectorAll('.progress-ring.is-open').forEach(item=>{item.classList.remove('is-open');item.setAttribute('aria-expanded','false');});}
function toggleProgressTip(item){openProgress=!item.classList.contains('is-open');item.classList.toggle('is-open',openProgress);item.setAttribute('aria-expanded',String(openProgress));}
[app,modal].forEach(root=>root.addEventListener('click',e=>{if(root===modal&&modal.classList.contains('exchange-modal')){audio.stopExchange();modal.close();return;}if(root===modal&&modal.classList.contains('draw-modal')){if(skipRevealClick){skipRevealClick=false;return;}const redraw=e.target.closest('[data-redraw]');if(redraw&&!redraw.disabled){doDraw(Number(redraw.dataset.redraw));return;}finishDrawReveal();audio.playClose();modal.close();return;}const b=e.target.closest('button');if(!b)return;if(b.dataset.openFilter){const key=b.dataset.openFilter,group=collectionFilterChoices(key,CHARACTERS);if(!group)return;modal.className='filter-modal';modal.setAttribute('aria-label',group.label);modal.innerHTML=collectionFilterMarkup(key,filter[key],CHARACTERS);modal.showModal();modal.querySelector('[aria-pressed="true"]').focus({preventScroll:true});return;}if(b.dataset.filterOption!==undefined){const key=b.dataset.filterKey,group=collectionFilterChoices(key,CHARACTERS);if(!group||!group.options.some(([value])=>value===b.dataset.filterOption))return;filter[key]=b.dataset.filterOption;modal.close();render();app.querySelector('[data-open-filter="'+key+'"]').focus({preventScroll:true});return;}if(b.dataset.currencyTip!==undefined){closeProgressTip();toggleCurrencyTip(b);return;}if(b.dataset.progressTip!==undefined){closeCurrencyTips();toggleProgressTip(b);return;}closeCurrencyTips();closeProgressTip();if(b.dataset.close!==undefined){modal.close();return;}if(b.dataset.rules!==undefined){showRules();return;}if(b.dataset.reset!==undefined){showReset();return;}if(b.dataset.confirmReset!==undefined){state=newSave();persist(state);modal.close();render();notify('进度已重置。');return;}if(b.dataset.export!==undefined){exportSave();return;}if(b.dataset.import!==undefined){importSave();return;}if(b.dataset.history!==undefined){view='history';clearInterval(timer);timer=null;render();return;}if(b.dataset.settings!==undefined){view='settings';clearInterval(timer);timer=null;render();return;}if(b.dataset.card){showDetail(b.dataset.card);return;}if(b.dataset.exchange){try{const candidate=validateSave(state),result=exchange(candidate,b.dataset.exchange);persist(candidate);state=candidate;render();showExchangeSuccess(result);}catch(error){showExchangeError(modal,error.message);}return;}if(b.dataset.redraw){doDraw(Number(b.dataset.redraw));return;}if(b.dataset.daily!==undefined){try{const amount=claimDaily(state);persist(state);render();notify('已领取 '+amount+' 晷签。');}catch(error){notify(error.message);}return;}if(b.dataset.collection!==undefined){view='collection';clearInterval(timer);timer=null;render();return;}if(b.dataset.home!==undefined){view='home';render();start();return;}if(b.dataset.i!==undefined){index=Number(b.dataset.i);render();}if(b.dataset.draw){doDraw(Number(b.dataset.draw));}}));
document.addEventListener('pointerdown',e=>{if(!e.target.closest('.wallet-item'))closeCurrencyTips();if(!e.target.closest('.progress-ring'))closeProgressTip();});
app.addEventListener('change',e=>{const key=e.target.dataset.setting;if(!key)return;state.settings[key]=e.target.checked;persist(state);audio.unlock();audio.sync();document.documentElement.classList.toggle('reduced',state.settings.reduced);if(key==='reduced'){clearInterval(timer);timer=null;if(!state.settings.reduced)start();}notify('设置已保存。');});
function advanceHomeCarousel(){
 if(view!=='home')return;
 const shell=app.querySelector('.demo-shell');if(!shell)return;
 index=(index+1)%ssr.length;
 const character=CHARACTERS[ssr[index].characterIndex];
 shell.querySelectorAll('.carousel-slide').forEach((slide,i)=>slide.classList.toggle('active',i===index));
 shell.querySelectorAll('.carousel-dots .dot-button').forEach((dot,i)=>dot.setAttribute('aria-current',String(i===index)));
 shell.querySelectorAll('.hero-choices button').forEach((choice,i)=>choice.setAttribute('aria-pressed',String(i===index)));
 shell.querySelector('.hero-copy .poem').textContent=character.motto;
 shell.querySelector('.featured .red-seal').textContent=character.seal;
 shell.querySelector('.featured small').textContent=character.office;
 shell.querySelector('.featured h2').textContent=ssr[index].displayName;
 shell.querySelector('.identity-copy').innerHTML=character.motto+'<br>'+character.description;
}
function start(){if(timer||state.settings.reduced||matchMedia('(prefers-reduced-motion: reduce)').matches)return;timer=setInterval(advanceHomeCarousel,4200);}
const portraitPhone=matchMedia('(orientation: portrait) and (max-width: 700px)');
function clearRotateTimers(){clearTimeout(rotateTimer);clearInterval(rotateTick);rotateTimer=null;rotateTick=null;}
function enterSoftLandscape(){if(!portraitPhone.matches)return;clearRotateTimers();rotatePrompt.classList.remove('is-counting');document.documentElement.classList.add('soft-landscape');try{screen.orientation?.lock?.('landscape')?.catch(()=>{});}catch{}}
function syncPhoneOrientation(){clearRotateTimers();if(!portraitPhone.matches){document.documentElement.classList.remove('soft-landscape');rotatePrompt.classList.remove('is-counting');return;}document.documentElement.classList.remove('soft-landscape');rotatePrompt.classList.add('is-counting');let seconds=3;rotateCountdown.textContent=seconds;rotateTick=setInterval(()=>{seconds-=1;if(seconds>0)rotateCountdown.textContent=seconds;},1000);rotateTimer=setTimeout(enterSoftLandscape,3000);}
if(portraitPhone.addEventListener)portraitPhone.addEventListener('change',syncPhoneOrientation);else portraitPhone.addListener?.(syncPhoneOrientation);window.addEventListener('orientationchange',()=>setTimeout(syncPhoneOrientation,120));
function syncVisibleViewport(){const viewport=window.visualViewport;if(viewport&&Math.abs(viewport.scale-1)>.05)return;const width=viewport?.width||innerWidth,height=viewport?.height||innerHeight,root=document.documentElement;root.style.setProperty('--visible-height',height+'px');root.style.setProperty('--visible-width',width+'px');root.classList.toggle('compact-landscape',width>height&&height<=600&&width<=1200);}
window.addEventListener('resize',syncVisibleViewport);window.visualViewport?.addEventListener('resize',syncVisibleViewport);
app.addEventListener('input',e=>{if(!e.target.matches('[data-volume]'))return;state.settings.volume=Number(e.target.value)/100;audio.sync();});
app.addEventListener('change',e=>{if(e.target.matches('[data-volume]'))persist(state);});
modal.addEventListener('cancel',e=>{if(!modal.classList.contains('draw-modal'))return;e.preventDefault();finishDrawReveal();audio.playClose();modal.close();});
modal.addEventListener('close',()=>{if(!modal.open){audio.stopExchange();document.documentElement.classList.remove('detail-open');}else if(!modal.matches('.detail-modal,.exchange-modal'))document.documentElement.classList.remove('detail-open');});
document.documentElement.classList.toggle('reduced',state.settings.reduced);render();start();syncPhoneOrientation();syncVisibleViewport();
