import {CARDS,CARD_BY_ID,CHARACTERS} from './data.js';
import {newSave,draw,progress,claimDaily,localDay,exchange,validateSave} from './engine.js';
import {loadSave,persist} from './storage.js';
import {pityCopy,starsMarkup} from './presentation.js';
const app=document.querySelector('#app'),modal=document.querySelector('#modal'),toast=document.querySelector('#toast'),rotatePrompt=document.querySelector('.rotate'),rotateCountdown=document.querySelector('.rotate-countdown');let state=loadSave().save||newSave(),index=0,view='home',timer,toastTimer,rotateTimer,rotateTick,openCurrency=null,filter={rarity:'all',role:'all',owned:'all'};
const ssr=CARDS.filter(c=>c.rarity==='SSR');
function sideNav(){return '<nav class="side-nav" aria-label="主要导航"><button data-home '+(view==='home'?'aria-current="page"':'')+'><b>晷</b><span>主页</span></button><button data-collection '+(view==='collection'?'aria-current="page"':'')+'><b>册</b><span>图鉴</span></button><button data-history '+(view==='history'?'aria-current="page"':'')+'><b>录</b><span>纪事</span></button><button data-settings '+(view==='settings'?'aria-current="page"':'')+'><b>设</b><span>设置</span></button></nav>';}
function currencyItems(){return [['晷签',state.tickets,'用于展卷的珍贵道具'],['印记',state.marks,'每一次展卷可获取一个，满100个可兑换SSR'],['余晖',state.glow,'满星卡溢出时获得的稀有道具，可用于兑换卡面']];}
function currencyItemsMarkup(){return currencyItems().map(([name,amount,tip])=>{const open=openCurrency===name;return '<button type="button" class="wallet-item'+(open?' is-open':'')+'" data-currency-tip="'+name+'" aria-expanded="'+open+'" aria-label="'+name+' '+amount+'，点击查看说明"><small>'+name+'</small><strong>'+amount+'</strong><span class="wallet-tip" role="tooltip">'+tip+'</span></button>';}).join('');}
function currencyStrip(){return '<span class="currency-strip" aria-label="持有货币">'+currencyItemsMarkup()+'</span>';}
function utilityHeader(title){return '<header class="collection-top"><span class="eyebrow">'+title+'</span>'+currencyStrip()+'</header>';}
function homeWallet(){return '<aside class="home-wallet" aria-label="持有货币">'+currencyItemsMarkup()+'</aside>';}
function historyPage(){const rows=state.history.map(h=>{const c=CARD_BY_ID[h.id],person=CHARACTERS[c.characterIndex];return '<div class="history-row '+c.rarity+'"><time>'+new Date(h.time).toLocaleString('zh-CN')+'</time><span class="history-rarity '+c.rarity+'">'+c.rarity+'</span><strong>'+person.name+' · '+c.title+'</strong><span>'+h.source+'</span><small>'+(h.glow?'余晖 +'+h.glow:h.before+' → '+h.after+' 星')+'</small></div>';}).join('')||'<p class="empty">尚未展卷。</p>';app.innerHTML=sideNav()+'<main class="utility-page">'+utilityHeader('展卷纪事')+'<section class="utility-heading"><h1>相逢有迹</h1><p>累计 '+state.totalDraws+' 抽 · 保存最近300次获得记录</p></section><div class="history-table">'+rows+'</div></main>';}
function settingsPage(){const toggles=[['fast','快速展卷','直接展示抽卡结果。'],['rareEffects','稀有卡强调','强化SSR结果的红金边框。'],['reduced','减少动态效果','关闭轮播和界面过渡。']].map(([key,title,desc])=>'<label class="setting-row"><span><b>'+title+'</b><small>'+desc+'</small></span><input type="checkbox" data-setting="'+key+'" '+(state.settings[key]?'checked':'')+'></label>').join('');app.innerHTML=sideNav()+'<main class="utility-page">'+utilityHeader('偏好与存档')+'<section class="utility-heading"><h1>设置</h1><p>进度保存在当前浏览器，建议定期导出备份。</p></section><div class="settings-panels"><section><h2>展卷体验</h2>'+toggles+'<div class="settings-actions"><button data-rules>查看抽取规则</button></div></section><section><h2>存档由你保管</h2><p>更换设备、网址或清理浏览器数据时，需要手动导入备份。</p><div class="settings-actions"><button data-export>导出存档</button><button class="primary" data-import>导入存档</button></div><hr><h3>重新开始</h3><p>恢复初始60张晷签，并清空当前收集、兑换与纪事记录。请先导出备份。</p><button class="danger" data-reset>重置进度</button></section></div></main>';}
function collection(){const p=progress(state),pct=Math.round(p.owned/95*100),visible=CARDS.filter(c=>{const n=state.copies[c.id]||0;return (filter.rarity==='all'||c.rarity===filter.rarity)&&(filter.role==='all'||c.characterId===filter.role)&&(filter.owned==='all'||filter.owned==='missing'&&n===0||filter.owned==='owned'&&n>0||filter.owned==='unfinished'&&n<c.max||filter.owned==='full'&&n>=c.max);}),cards=visible.map(c=>{const n=state.copies[c.id]||0,person=CHARACTERS[c.characterIndex];return '<button class="collection-card '+c.rarity+'" data-card="'+c.id+'"><img src="'+c.art+'" alt="'+person.name+'·'+c.title+'"><span class="collection-rarity">'+c.rarity+'</span><div><small>'+person.name+'</small><strong>'+c.title+'</strong>'+starsMarkup(c.rarity,n)+'</div></button>';}).join('')||'<p class="empty">没有符合筛选条件的卡牌。</p>';const rarityOptions=['all','SSR','SR','R','N'].map(v=>'<option value="'+v+'" '+(filter.rarity===v?'selected':'')+'>'+(v==='all'?'全部':v)+'</option>').join(''),roleOptions='<option value="all">全部人物</option>'+CHARACTERS.map(c=>'<option value="'+c.id+'" '+(filter.role===c.id?'selected':'')+'>'+c.name+'</option>').join(''),ownedOptions=[['all','全部状态'],['missing','未获得'],['owned','已获得'],['unfinished','未满星'],['full','已满星']].map(([v,t])=>'<option value="'+v+'" '+(filter.owned===v?'selected':'')+'>'+t+'</option>').join('');app.innerHTML=sideNav()+'<main class="collection-page"><header class="collection-top"><span class="eyebrow">珍藏此间</span>'+currencyStrip()+'</header><section class="collection-heading"><div><h1>百卷图鉴 <span class="ring" style="--pct:'+pct+'%"><b>'+pct+'%</b></span></h1><p>收录 '+p.owned+' / 95 卷 · 满星 '+p.full+' / 95 卷 · 点击卡面可查看并兑换</p></div></section><div class="collection-filters"><label>稀有度<select data-filter="rarity">'+rarityOptions+'</select></label><label>人物<select data-filter="role">'+roleOptions+'</select></label><label>收集<select data-filter="owned">'+ownedOptions+'</select></label><span>'+visible.length+' 卷</span></div><div class="collection-grid">'+cards+'</div></main>';}
function render(){if(view==='collection'){collection();return;}if(view==='history'){historyPage();return;}if(view==='settings'){settingsPage();return;}const p=progress(state),c=CHARACTERS[ssr[index].characterIndex];const slides=ssr.map((x,i)=>'<img class="carousel-slide '+(i===index?'active':'')+'" src="'+x.art+'" alt="'+CHARACTERS[x.characterIndex].name+' SSR卡面">').join('');const dots=ssr.map((x,i)=>'<button class="dot-button" data-i="'+i+'" aria-current="'+(i===index)+'"><span></span></button>').join('');const choices=ssr.map((x,i)=>'<button data-i="'+i+'"><img src="'+x.art+'" alt=""><span>'+CHARACTERS[x.characterIndex].name+'</span></button>').join('');app.innerHTML=sideNav()+'<main class="demo-shell"><div class="home-wash"></div>'+homeWallet()+'<div class="hero-copy"><span class="eyebrow">常驻卡池 / 壹</span><div class="hero-title"><h1>一卷<span>山河</span></h1><button class="daily-gift" data-daily '+(state.lastClaim>=localDay()?'disabled':'')+'>'+(state.lastClaim>=localDay()?'今日签赠已领':'领取今日赠签')+'</button></div><p class="poem">'+c.motto+'</p><p class="intro">循光展卷，收录此间风华。<br>五位故人，九十五卷，皆可免费收集。</p></div><section class="hero-carousel"><div class="carousel-stage">'+slides+'</div><div class="carousel-dots">'+dots+'</div></section><aside class="identity-dock"><div class="featured"><span class="red-seal">'+c.seal+'</span><div><small>'+c.office+'</small><h2>'+c.name+'</h2></div></div><p class="identity-copy">'+c.motto+'<br>'+c.description+'</p><div class="hero-choices">'+choices+'</div><button class="collection-link" data-collection>图鉴　'+p.owned+' / 95</button></aside><div class="draw-dock"><div class="journey"><span>图鉴进度</span><strong>'+p.owned+'<small> / 95</small></strong><div class="track"><span style="width:'+(p.owned/95*100)+'%"></span></div></div><div class="pull-area"><div class="pity"><span>'+pityCopy(state.pity).ssr+'</span><span>'+pityCopy(state.pity).sr+'</span></div><div class="pull-buttons"><button data-draw="1" '+(state.tickets<1?'disabled':'')+'>展卷一次<small>晷签 × 1</small></button><button class="primary" data-draw="10" '+(state.tickets<10?'disabled':'')+'>展卷十次<small>晷签 × 10</small></button></div><small class="hint">'+pityCopy(state.pity).shared+'</small></div></div></main>';}
function notify(message){toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),3200);}
function showResults(items,count){const cards=items.map(r=>{const c=CARD_BY_ID[r.id],person=CHARACTERS[c.characterIndex];return '<article class="result-card '+c.rarity+'"><img src="'+c.art+'" alt="'+person.name+'·'+c.title+'"><span class="collection-rarity">'+c.rarity+'</span>'+(r.isNew?'<em>初见</em>':'')+'<div><small>'+person.name+'</small><strong>'+c.title+'</strong>'+starsMarkup(c.rarity,r.after)+'</div></article>';}).join('');modal.className='draw-modal '+(count===10?'ten-pull-modal':'single-pull-modal')+(items.length>10?' bonus-result':'');modal.innerHTML='<header class="modal-head"><h2>此番相逢</h2><button data-close>关闭 ×</button></header><p class="result-summary">消耗 '+count+' 晷签 · 获得 '+items.length+' 份 · 印记 +'+count+'</p><div class="draw-results">'+cards+'</div><div class="result-actions"><button data-close>收入图鉴</button><button class="primary" data-redraw="10" '+(state.tickets<10?'disabled':'')+'>再展十卷</button></div>';if(!modal.open)modal.showModal();}
function showDetail(id){const c=CARD_BY_ID[id],person=CHARACTERS[c.characterIndex],n=state.copies[id]||0,cost=c.rarity==='SSR'?100:{SR:80,R:30,N:10}[c.rarity],currency=c.rarity==='SSR'?'印记':'余晖',full=n>=c.max;modal.className='';modal.innerHTML='<header class="modal-head"><h2>'+person.name+' · '+c.title+'</h2><button data-close>关闭 ×</button></header><div class="card-detail"><img src="'+c.art+'" alt="'+person.name+'·'+c.title+'"><div><span class="collection-rarity">'+c.rarity+'</span><p>'+c.description+'</p>'+starsMarkup(c.rarity,n)+'<p>'+(full?'已满星':'再次获得一份将自动点亮下一颗星。')+'</p><button class="primary" data-exchange="'+id+'" '+(full?'disabled':'')+'>兑换一份 · '+cost+currency+'</button></div></div>';if(!modal.open)modal.showModal();}
function showRules(){modal.className='';modal.innerHTML='<header class="modal-head"><h2>抽取规则</h2><button data-close>关闭 ×</button></header><div class="rules-copy"><h3>单一卡池</h3><p>SSR 1.5%、SR 3.5%、R 25%、N 70%。</p><h3>保底</h3><p>SSR最多60抽获得。每十抽至少获得一张SR；单抽与十连都享有SR保底机制，十连中出现的SSR不能替代保底SR。</p><h3>满星与兑换</h3><p>满星卡仍留在卡池，但会降低满星卡的出卡概率。每抽获得1印记，100印记可兑换任意未满星SSR卡一张；余晖可兑换N、R、SR卡。</p></div>';if(!modal.open)modal.showModal();}
function showReset(){modal.className='';modal.innerHTML='<header class="modal-head"><h2>确认重新开始</h2><button data-close>关闭 ×</button></header><div class="reset-confirm"><p>这会清空当前收集、晷签、印记、余晖与纪事记录，并恢复初始60张晷签。</p><p>此操作无法自动撤销，建议先导出存档。</p><div class="result-actions"><button data-close>取消</button><button class="danger" data-confirm-reset>确认重置</button></div></div>';if(!modal.open)modal.showModal();}
function doDraw(count){try{const items=draw(state,count);persist(state);render();showResults(items,count);}catch(error){notify(error.message);}}
function exportSave(){const blob=new Blob([JSON.stringify({format:'rigui-save',exportedAt:new Date().toISOString(),save:state},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='日晷存档-'+localDay()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function importSave(){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{try{const raw=JSON.parse(await input.files[0].text()),candidate=validateSave(raw);state=candidate;persist(state);render();notify('存档已导入。');}catch(error){notify(error.message||'存档导入失败。');}};input.click();}
function closeCurrencyTips(except){if(!except)openCurrency=null;document.querySelectorAll('.wallet-item.is-open').forEach(item=>{if(item!==except){item.classList.remove('is-open');item.setAttribute('aria-expanded','false');}});}
function toggleCurrencyTip(item){const shouldOpen=!item.classList.contains('is-open');closeCurrencyTips(item);openCurrency=shouldOpen?item.dataset.currencyTip:null;item.classList.toggle('is-open',shouldOpen);item.setAttribute('aria-expanded',String(shouldOpen));}
[app,modal].forEach(root=>root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.currencyTip!==undefined){toggleCurrencyTip(b);return;}closeCurrencyTips();if(b.dataset.close!==undefined){modal.close();return;}if(b.dataset.rules!==undefined){showRules();return;}if(b.dataset.reset!==undefined){showReset();return;}if(b.dataset.confirmReset!==undefined){state=newSave();persist(state);modal.close();render();notify('进度已重置。');return;}if(b.dataset.export!==undefined){exportSave();return;}if(b.dataset.import!==undefined){importSave();return;}if(b.dataset.history!==undefined){view='history';clearInterval(timer);timer=null;render();return;}if(b.dataset.settings!==undefined){view='settings';clearInterval(timer);timer=null;render();return;}if(b.dataset.card){showDetail(b.dataset.card);return;}if(b.dataset.exchange){try{exchange(state,b.dataset.exchange);persist(state);render();showDetail(b.dataset.exchange);notify('兑换成功，已收入图鉴。');}catch(error){notify(error.message);}return;}if(b.dataset.redraw){doDraw(Number(b.dataset.redraw));return;}if(b.dataset.daily!==undefined){try{const amount=claimDaily(state);persist(state);render();notify('已领取 '+amount+' 晷签。');}catch(error){notify(error.message);}return;}if(b.dataset.collection!==undefined){view='collection';clearInterval(timer);timer=null;render();return;}if(b.dataset.home!==undefined){view='home';render();start();return;}if(b.dataset.i!==undefined){index=Number(b.dataset.i);render();}if(b.dataset.draw){doDraw(Number(b.dataset.draw));}}));
document.addEventListener('pointerdown',e=>{if(!e.target.closest('.wallet-item'))closeCurrencyTips();});
app.addEventListener('change',e=>{const filterKey=e.target.dataset.filter;if(filterKey){filter[filterKey]=e.target.value;render();return;}const key=e.target.dataset.setting;if(!key)return;state.settings[key]=e.target.checked;persist(state);document.documentElement.classList.toggle('reduced',state.settings.reduced);if(key==='reduced'){clearInterval(timer);timer=null;if(!state.settings.reduced)start();}notify('设置已保存。');});
function start(){if(timer||state.settings.reduced||matchMedia('(prefers-reduced-motion: reduce)').matches)return;timer=setInterval(()=>{if(view==='home'){index=(index+1)%ssr.length;render();}},4200);}
const portraitPhone=matchMedia('(orientation: portrait) and (max-width: 700px)');
function clearRotateTimers(){clearTimeout(rotateTimer);clearInterval(rotateTick);rotateTimer=null;rotateTick=null;}
function enterSoftLandscape(){if(!portraitPhone.matches)return;clearRotateTimers();rotatePrompt.classList.remove('is-counting');document.documentElement.classList.add('soft-landscape');try{screen.orientation?.lock?.('landscape')?.catch(()=>{});}catch{}}
function syncPhoneOrientation(){clearRotateTimers();if(!portraitPhone.matches){document.documentElement.classList.remove('soft-landscape');rotatePrompt.classList.remove('is-counting');return;}document.documentElement.classList.remove('soft-landscape');rotatePrompt.classList.add('is-counting');let seconds=3;rotateCountdown.textContent=seconds;rotateTick=setInterval(()=>{seconds-=1;if(seconds>0)rotateCountdown.textContent=seconds;},1000);rotateTimer=setTimeout(enterSoftLandscape,3000);}
if(portraitPhone.addEventListener)portraitPhone.addEventListener('change',syncPhoneOrientation);else portraitPhone.addListener?.(syncPhoneOrientation);window.addEventListener('orientationchange',()=>setTimeout(syncPhoneOrientation,120));
function syncVisibleViewport(){const viewport=window.visualViewport;if(viewport&&Math.abs(viewport.scale-1)>.05)return;const width=viewport?.width||innerWidth,height=viewport?.height||innerHeight,root=document.documentElement;root.style.setProperty('--visible-height',height+'px');root.classList.toggle('compact-landscape',width>height&&height<=600&&width<=1200);}
window.addEventListener('resize',syncVisibleViewport);window.visualViewport?.addEventListener('resize',syncVisibleViewport);
document.documentElement.classList.toggle('reduced',state.settings.reduced);render();start();syncPhoneOrientation();syncVisibleViewport();
